#!/bin/bash


# In this section configure deployment specific settings
# BEGIN
module load python/3.7.3
. ~/.virtualenvs/easyvvuq-qcgpj/bin/activate
# END

# Do not change everything below
python3.7 -m easyvvuq.execution.qcgpj.pj_utils.easyvvuq_encode $@
