#!/bin/bash

# In this section configure deployment specific settings
# BEGIN
#module load python/3.6.4
#. ~/.virtualenvs/easyvvuq-qcgpj/bin/activate
# END

# Do not change everything below
python -m easyvvuq.execution.qcgpj.pj_utils.easyvvuq_execute $@
