!> ETS + Update EQ + CHEASE
!
!> Inputs:  
!     ets_coreprof_in.cpo
!     ets_equilibrium_in.cpo
!     ets_coreimpur_in.cpo
!     ets_coretransp_in.cpo
!     ets_toroidfield_in.cpo
!     ets_coresource_in.cpo (if not given gaussian_source will be used)
!
!> Output: 
!     chease_equilibrium_out.cpo 


program ets_chease

  use euitm_schemas,   only: type_coreprof,    & 
                          &  type_equilibrium, &
                          &  type_coretransp,  &
                          &  type_coresource,  &
                          &  type_coreimpur,   &
                          &  type_toroidfield
  use read_structures, only: open_read_file,  &
                          &  close_read_file, &
                          &  read_cpo
  use write_structures, only: open_write_file,  &
                           &  close_write_file, &
                           &  write_cpo

  use deallocate_structures, only: deallocate_cpo

  use copy_structures, only: copy_cpo

  use ets_standalone,         only: ets_cpo
  use equilupdate_standalone, only: equilupdate2cpo
  use chease_standalone,      only: chease_cpo
  use sources_standalone,     only: gaussian_source_cpo

implicit none

  ! CPO files
  character(len=*), parameter :: corep_file_in   = "ets_coreprof_in.cpo"
  character(len=*), parameter :: equil_file_in   = "ets_equilibrium_in.cpo"
  character(len=*), parameter :: cores_file_in   = "ets_coresource_in.cpo"
  character(len=*), parameter :: corei_file_in   = "ets_coreimpur_in.cpo"
  character(len=*), parameter :: coret_file_in   = "ets_coretransp_in.cpo"
  character(len=*), parameter :: toroidf_file_in = "ets_toroidfield_in.cpo"
  character(len=*), parameter :: equil_file_out = "chease_equilibrium_out.cpo"

  type(type_coreprof),    pointer :: corep_in(:)     => null()
  type(type_coreprof),    pointer :: corep_ets(:)    => null()
  type(type_coretransp),  pointer :: coret_in(:)     => null()
  type(type_coresource),  pointer :: cores_in(:)     => null()
  type(type_coreimpur),   pointer :: corei_in(:)     => null()
  type(type_equilibrium), pointer :: equil_in(:)     => null()
  type(type_equilibrium), pointer :: equil_update(:) => null() 
  type(type_equilibrium), pointer :: equil_chease(:) => null()
  type(type_toroidfield), pointer :: toroidf_in(:)   => null()

  integer :: ios, it

  !... Read initial CPOs
  allocate(corep_in(1))
  allocate(coret_in(1))
  allocate(cores_in(1))
  allocate(corei_in(1))
  allocate(equil_in(1))
  allocate(toroidf_in(1))

  open (unit = 10, file = corep_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (10)
     call open_read_file(10, corep_file_in)
     call read_cpo(corep_in(1), 'coreprof' )
     call close_read_file
  end if

  open (unit = 11, file = coret_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (11)
     call open_read_file(11, coret_file_in)
     call read_cpo(coret_in(1), 'coretransp' )
     call close_read_file
  end if

  open (unit = 12, file = corei_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (12)
     call open_read_file(12, corei_file_in)
     call read_cpo(corei_in(1), 'coreimpur' )
     call close_read_file
  end if

  open (unit = 13, file = equil_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (13)
     call open_read_file(13, equil_file_in)
     call read_cpo(equil_in(1), 'equilibrium' )
     call close_read_file
  end if

  open (unit = 14, file = toroidf_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (14)
     call open_read_file(14, toroidf_file_in)
     call read_cpo(toroidf_in(1), 'toroidfield' )
     call close_read_file
  end if

  open (unit = 15, file = cores_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (15)
     call open_read_file(15, cores_file_in)
     call read_cpo(cores_in(1), 'coresource' )
     call close_read_file
  else
      ! CPO file not found, cores_in will be generated by gaussian_source_cpo 
      call gaussian_source_cpo(corep_in, equil_in, cores_in)
  end if

  ! ETS
  call ets_cpo(corep_in, equil_in, coret_in, cores_in, corei_in, corep_ets)

  ! EQUILUPDATE
  call equilupdate2cpo(corep_ets, toroidf_in, equil_in, equil_update)

  ! CHEASE
  call chease_cpo(equil_update, equil_chease)
  
  ! Save output CPO
  call open_write_file(20, equil_file_out)
  call write_cpo(equil_chease(1),'equilibrium')
  call close_write_file

  call deallocate_cpo(corep_in)
  call deallocate_cpo(corep_ets)
  call deallocate_cpo(coret_in)
  call deallocate_cpo(equil_in)
  call deallocate_cpo(equil_update)
  call deallocate_cpo(equil_chease)
  call deallocate_cpo(cores_in)
  call deallocate_cpo(corei_in)
  call deallocate_cpo(toroidf_in)

end program ets_chease

