!> Box for: GEM
!
!> Inputs:  
!     gem_coreprof_in.cpo
!     gem_equilibrium_in.cpo
!     gem_coretransp_in.cpo
!
!> Output: 
!     gem_coreprof_out 


program loop_gem_notransp

  use euitm_schemas,   only: type_coreprof,    & 
                          &  type_equilibrium, &
                          &  type_coretransp
  use read_structures, only: open_read_file,  &
                          &  close_read_file, &
                          &  read_cpo
  use write_structures, only: open_write_file,  &
                           &  close_write_file, &
                           &  write_cpo

  use deallocate_structures, only: deallocate_cpo

  use copy_structures, only: copy_cpo

  use gem_standalone,         only: gem_cpo
  use imp4dv_standalone,      only: imp4dv_cpo

  use mpi

implicit none

  ! CPO files
  character(len=*), parameter :: corep_file_in   = "gem_coreprof_in.cpo"
  character(len=*), parameter :: equil_file_in   = "gem_equilibrium_in.cpo"
  character(len=*), parameter :: coret_file_in   = "gem_coretransp_in.cpo"

  integer, parameter :: STEPS = 500
  logical, parameter :: TIMETRACE = .TRUE.

  ! If TRUE, coresource will be generated by gaussian_source_cpo
  !logical, parameter :: GAUSSIAN_SOURCE = .FALSE.

  type(type_coreprof),    pointer :: corep_in(:)     => null()
  type(type_coreprof),    pointer :: corep_ets(:)    => null()
  type(type_coretransp),  pointer :: coret_in(:)     => null()
  type(type_coretransp),  pointer :: coret_gem(:)    => null()
  type(type_coretransp),  pointer :: coret_imp4dv(:) => null()
  type(type_equilibrium), pointer :: equil_in(:)     => null() 
  type(type_equilibrium), pointer :: equil_chease(:) => null()

  integer :: ios, it, ierr, npes, irank
  character(4)  :: itstr
  
  call MPI_Init(ierr)
  call MPI_Comm_size(MPI_COMM_WORLD, npes, ierr)
  call MPI_Comm_rank(MPI_COMM_WORLD, irank, ierr)

  !... Read initial CPOs
  allocate(corep_in(1))
  allocate(coret_in(1))
  allocate(equil_in(1))

  open (unit = 10, file = corep_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (10)
     call open_read_file(10, corep_file_in)
     call read_cpo(corep_in(1), 'coreprof' )
     call close_read_file
  end if

  open (unit = 11, file = coret_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (11)
     call open_read_file(11, coret_file_in)
     call read_cpo(coret_in(1), 'coretransp' )
     call close_read_file
  end if

  open (unit = 13, file = equil_file_in, &
       status = 'old', form = 'formatted', &
       action = 'read', iostat = ios)
  if (ios == 0) then
     close (13)
     call open_read_file(13, equil_file_in)
     call read_cpo(equil_in(1), 'equilibrium' )
     call close_read_file
  end if

  ! Loop
  allocate(corep_ets(1))
  allocate(equil_chease(1))
  allocate(coret_imp4dv(1))
  call copy_cpo(corep_in(1),corep_ets(1))
  call copy_cpo(equil_in(1),equil_chease(1))
  call copy_cpo(coret_in(1),coret_imp4dv(1))

  do it=1, STEPS

     if (irank.eq.0) then
      write(itstr,'(I4.4)') it
      print *,"**** iteration = "//itstr//" ****"
     end if

     ! GEM
     call deallocate_cpo(coret_gem)
     nullify(coret_gem)
     call gem_cpo(equil_chease, corep_ets, coret_gem)
     
     if ((irank.eq.0).AND.(TIMETRACE)) then
        call open_write_file(23, 'gem_coretransp_'//itstr//'.cpo')
        call write_cpo(coret_gem(1),'coretransp')
        call close_write_file
     end if

     ! IMP4DV
     call deallocate_cpo(coret_imp4dv)
     nullify(coret_imp4dv)
     call imp4dv_cpo(equil_chease, corep_ets, coret_gem, coret_imp4dv)

     if ((irank.eq.0).AND.(TIMETRACE)) then
        call open_write_file(24, 'imp4dv_coretransp_'//itstr//'.cpo')
        call write_cpo(coret_imp4dv(1),'coretransp')
        call close_write_file
     end if

  end do

  if ((irank.eq.0).AND.(.not.TIMETRACE)) then
    call open_write_file(20, 'gem_coretransp_out.cpo')
    call write_cpo(coret_gem(1),'coretransp')
    call close_write_file
  end if

  call deallocate_cpo(corep_in)
  call deallocate_cpo(corep_ets)
  call deallocate_cpo(coret_in)
  call deallocate_cpo(coret_gem)
  call deallocate_cpo(coret_imp4dv)
  call deallocate_cpo(equil_in)
  call deallocate_cpo(equil_chease)
  
  call MPI_Finalize(ierr)

end program loop_gem_notransp
